"""update last_update to datetime

Revision ID: d960d00c07e8
Revises: 5dafda39c790
Create Date: 2025-10-02 19:31:14.931764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd960d00c07e8'
down_revision = '5dafda39c790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
